/* Creación de base de datos y tablas */
USE master;
GO

DROP DATABASE IF EXISTS Clinica;

CREATE DATABASE Clinica;
GO

USE Clinica;
GO

CREATE TABLE Paciente(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(60) NOT NULL,
	Apellido VARCHAR(60) NOT NULL,
	Peso DECIMAL(6,2) NOT NULL,
	Altura DECIMAL(6,2) NOT NULL,
	FechaNacimiento DATE NOT NULL
);

CREATE TABLE Doctor(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(60) NOT NULL,
	Apellido VARCHAR(60) NOT NULL,
	Especialidad VARCHAR(60) NOT NULL
);

CREATE TABLE Cita(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	FechaConsulta DATETIME NOT NULL,
	PacienteId INT NOT NULL,
	DoctorId INT NOT NULL

	CONSTRAINT FK_Cita_Paciente FOREIGN KEY(PacienteId) REFERENCES Paciente(Id),
	CONSTRAINT FK_Cita_Doctor FOREIGN KEY(DoctorId) REFERENCES Doctor(Id)
);

CREATE TABLE Consulta(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Diagnostico VARCHAR(60) NOT NULL,
	CitaId INT NOT NULL

	CONSTRAINT FK_Consulta_Cita FOREIGN KEY(CitaId) REFERENCES Cita(Id)
);
